version: "3"

services:
  web:
    build: .
    image: improv-jaa/improfestival-2017
    ports:
      - 8081:8080
    volumes:
      - ./_site:/usr/share/nginx/html:ro
    # A random UID that does not exist
    user: "1109"
